version: '3.8'

services:

  postgres:
    build:
      context: docker/services/postgres
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=com.godeltech.bikesharing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: docker/services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/com.godeltech.bikesharing
    image: 'app'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data: