version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bikesharing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "d-base:/var/lib/postgresql/data"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    restart: always
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # web ui
    restart: always
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  bike-sharing:
    build:
      context: bikesharing-backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/bikesharing
      - SPRING_RABBITMQ_HOST=rabbitmq
    image: bike-sharing
    container_name: bike-sharing
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - bike-sharing:/data

volumes:
  d-base:
  bike-sharing: