server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bikesharing}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    contexts: dev

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    org.hibernateSQL: debug