server:
  port: ${PORT:8080}
spring:
  datasource:
    db-name: bikesharing
    host: localhost
    port: 5432
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    contexts: dev
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  mail:
    host: 127.0.0.1
    port: 1025 #2525
    report-type: XLSX
    sender: application@test.com
    recipients: admin@test.com,manager@test.com
    username:
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 60000
          timeout: 60000
          auth: false
          starttls:
            enable: false

logging:
  level:
    org.hibernate.SQL: debug